### ISSUE TITLE
SDWebImage版本问题

### ISSUE THREAD

**Issue by scholar-ink** [weexteam/weexpack-iOS#3]
模板生成的SDWebImage  pod 引入的是3.7.5 不是最新版本，最新版本 有更新downloadImageWithURL方法 导致和集成的其他sdk 有冲突

**Comment by erha19** [comment]
Merge #4

**Comment by scholar-ink** [comment]
咦~我看到SDWebImage 依然是3.7.5的版本，为啥会关闭这个问题呢？

**Comment by erha19** [comment]
@scholar-ink Go here (https://github.com/weexteam/weex-toolkit/issues/212) and do not repeat the discussion.
